create type "public"."feature_priority" as enum ('low', 'medium', 'high', 'critical');

create type "public"."feature_status" as enum ('backlog', 'in_progress', 'completed', 'testing', 'archived', 'cancelled');

create type "public"."project_priority" as enum ('high', 'medium', 'low', 'critical');

create type "public"."project_status" as enum ('active', 'completed', 'paused', 'archived', 'cancelled');

create type "public"."project_visibility" as enum ('public', 'private');

create type "public"."task_priority" as enum ('low', 'medium', 'high', 'critical');

create type "public"."task_status" as enum ('backlog', 'in_progress', 'completed', 'testing', 'archived', 'cancelled');

create type "public"."user_role" as enum ('admin', 'manager', 'member');

create table "public"."comment" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "author_id" uuid not null,
    "task_id" bigint,
    "feature_id" bigint,
    "content" character varying not null,
    "last_updated" timestamp with time zone not null default now()
);


alter table "public"."comment" enable row level security;

create table "public"."feature" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "description" character varying,
    "project_id" bigint not null,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "last_updated" timestamp with time zone not null default now(),
    "time_estimate" integer,
    "time_logged" integer,
    "status" feature_status not null default 'backlog'::feature_status,
    "priority" project_priority
);


alter table "public"."feature" enable row level security;

create table "public"."feature_dependencies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "dependent_id" bigint not null,
    "dependent_upon_id" bigint not null
);


alter table "public"."feature_dependencies" enable row level security;

create table "public"."file_comment" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "comment_id" bigint not null,
    "uploader_id" uuid not null,
    "name" character varying not null,
    "file_type" character varying not null,
    "file_path" character varying not null
);


alter table "public"."file_comment" enable row level security;

create table "public"."profile" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "email" character varying not null,
    "first_name" character varying,
    "last_name" character varying,
    "pfp" character varying,
    "last_login" timestamp with time zone,
    "phone_number" character varying,
    "bio" character varying,
    "skills" character varying[]
);


alter table "public"."profile" enable row level security;

create table "public"."profile_project" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" uuid not null,
    "project_id" bigint not null,
    "user_role" user_role not null
);


alter table "public"."profile_project" enable row level security;

create table "public"."profile_workspace" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" uuid not null,
    "workspace_id" bigint not null,
    "user_role" user_role not null
);


alter table "public"."profile_workspace" enable row level security;

create table "public"."project" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "description" character varying,
    "workspace_id" bigint not null,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "owner_id" uuid not null,
    "completion_percentage" smallint not null default '0'::smallint,
    "last_updated" timestamp with time zone not null default now(),
    "status" project_status not null default 'active'::project_status,
    "priority" project_priority,
    "visibility" project_visibility not null default 'public'::project_visibility
);


alter table "public"."project" enable row level security;

create table "public"."project_projecttag" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "project_id" bigint not null,
    "projecttag_id" bigint not null
);


alter table "public"."project_projecttag" enable row level security;

create table "public"."projecttag" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "description" character varying
);


alter table "public"."projecttag" enable row level security;

create table "public"."task" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "description" character varying,
    "project_id" bigint not null,
    "feature_id" bigint,
    "assignee_id" uuid,
    "start_date" timestamp with time zone,
    "due_date" timestamp with time zone,
    "completion_date" timestamp with time zone,
    "last_updated" timestamp with time zone,
    "time_estimate" integer,
    "time_logged" integer,
    "status" task_status not null default 'backlog'::task_status,
    "priority" task_priority
);


alter table "public"."task" enable row level security;

create table "public"."task_dependencies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "dependent_id" bigint not null,
    "dependent_upon_id" bigint not null
);


alter table "public"."task_dependencies" enable row level security;

create table "public"."workspace" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "description" character varying,
    "owner_id" uuid not null
);


alter table "public"."workspace" enable row level security;

CREATE UNIQUE INDEX comment_pkey ON public.comment USING btree (id);

CREATE UNIQUE INDEX feature_dependencies_pkey ON public.feature_dependencies USING btree (id);

CREATE UNIQUE INDEX feature_pkey ON public.feature USING btree (id);

CREATE UNIQUE INDEX file_comment_pkey ON public.file_comment USING btree (id);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id);

CREATE UNIQUE INDEX profile_project_pkey ON public.profile_project USING btree (id);

CREATE UNIQUE INDEX profile_workspace_pkey ON public.profile_workspace USING btree (id);

CREATE UNIQUE INDEX project_pkey ON public.project USING btree (id);

CREATE UNIQUE INDEX project_projecttag_pkey ON public.project_projecttag USING btree (id);

CREATE UNIQUE INDEX projecttag_pkey ON public.projecttag USING btree (id);

CREATE UNIQUE INDEX task_dependencies_pkey ON public.task_dependencies USING btree (id);

CREATE UNIQUE INDEX task_pkey ON public.task USING btree (id);

CREATE UNIQUE INDEX workspace_pkey ON public.workspace USING btree (id);

alter table "public"."comment" add constraint "comment_pkey" PRIMARY KEY using index "comment_pkey";

alter table "public"."feature" add constraint "feature_pkey" PRIMARY KEY using index "feature_pkey";

alter table "public"."feature_dependencies" add constraint "feature_dependencies_pkey" PRIMARY KEY using index "feature_dependencies_pkey";

alter table "public"."file_comment" add constraint "file_comment_pkey" PRIMARY KEY using index "file_comment_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."profile_project" add constraint "profile_project_pkey" PRIMARY KEY using index "profile_project_pkey";

alter table "public"."profile_workspace" add constraint "profile_workspace_pkey" PRIMARY KEY using index "profile_workspace_pkey";

alter table "public"."project" add constraint "project_pkey" PRIMARY KEY using index "project_pkey";

alter table "public"."project_projecttag" add constraint "project_projecttag_pkey" PRIMARY KEY using index "project_projecttag_pkey";

alter table "public"."projecttag" add constraint "projecttag_pkey" PRIMARY KEY using index "projecttag_pkey";

alter table "public"."task" add constraint "task_pkey" PRIMARY KEY using index "task_pkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_pkey" PRIMARY KEY using index "task_dependencies_pkey";

alter table "public"."workspace" add constraint "workspace_pkey" PRIMARY KEY using index "workspace_pkey";

alter table "public"."comment" add constraint "comment_author_id_fkey" FOREIGN KEY (author_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment" validate constraint "comment_author_id_fkey";

alter table "public"."comment" add constraint "comment_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment" validate constraint "comment_feature_id_fkey";

alter table "public"."comment" add constraint "comment_task_id_fkey" FOREIGN KEY (task_id) REFERENCES task(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment" validate constraint "comment_task_id_fkey";

alter table "public"."feature" add constraint "feature_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."feature" validate constraint "feature_project_id_fkey";

alter table "public"."feature_dependencies" add constraint "feature_dependencies_dependent_id_fkey" FOREIGN KEY (dependent_id) REFERENCES feature(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."feature_dependencies" validate constraint "feature_dependencies_dependent_id_fkey";

alter table "public"."feature_dependencies" add constraint "feature_dependencies_dependent_upon_id_fkey" FOREIGN KEY (dependent_upon_id) REFERENCES feature(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."feature_dependencies" validate constraint "feature_dependencies_dependent_upon_id_fkey";

alter table "public"."file_comment" add constraint "file_comment_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES comment(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."file_comment" validate constraint "file_comment_comment_id_fkey";

alter table "public"."file_comment" add constraint "file_comment_uploader_id_fkey" FOREIGN KEY (uploader_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."file_comment" validate constraint "file_comment_uploader_id_fkey";

alter table "public"."profile" add constraint "profile_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile" validate constraint "profile_id_fkey";

alter table "public"."profile_project" add constraint "profile_project_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_project" validate constraint "profile_project_profile_id_fkey";

alter table "public"."profile_project" add constraint "profile_project_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_project" validate constraint "profile_project_project_id_fkey";

alter table "public"."profile_workspace" add constraint "profile_workspace_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_workspace" validate constraint "profile_workspace_profile_id_fkey";

alter table "public"."profile_workspace" add constraint "profile_workspace_workspace_id_fkey" FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_workspace" validate constraint "profile_workspace_workspace_id_fkey";

alter table "public"."project" add constraint "project_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."project" validate constraint "project_owner_id_fkey";

alter table "public"."project" add constraint "project_workspace_id_fkey" FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."project" validate constraint "project_workspace_id_fkey";

alter table "public"."project_projecttag" add constraint "project_projecttag_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."project_projecttag" validate constraint "project_projecttag_project_id_fkey";

alter table "public"."project_projecttag" add constraint "project_projecttag_projecttag_id_fkey" FOREIGN KEY (projecttag_id) REFERENCES projecttag(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."project_projecttag" validate constraint "project_projecttag_projecttag_id_fkey";

alter table "public"."task" add constraint "task_assignee_id_fkey" FOREIGN KEY (assignee_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task" validate constraint "task_assignee_id_fkey";

alter table "public"."task" add constraint "task_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task" validate constraint "task_feature_id_fkey";

alter table "public"."task" add constraint "task_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task" validate constraint "task_project_id_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_dependent_id_fkey" FOREIGN KEY (dependent_id) REFERENCES task(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_dependent_id_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_dependent_upon_id_fkey" FOREIGN KEY (dependent_upon_id) REFERENCES task(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_dependent_upon_id_fkey";

alter table "public"."workspace" add constraint "workspace_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES profile(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workspace" validate constraint "workspace_owner_id_fkey";

grant delete on table "public"."comment" to "anon";

grant insert on table "public"."comment" to "anon";

grant references on table "public"."comment" to "anon";

grant select on table "public"."comment" to "anon";

grant trigger on table "public"."comment" to "anon";

grant truncate on table "public"."comment" to "anon";

grant update on table "public"."comment" to "anon";

grant delete on table "public"."comment" to "authenticated";

grant insert on table "public"."comment" to "authenticated";

grant references on table "public"."comment" to "authenticated";

grant select on table "public"."comment" to "authenticated";

grant trigger on table "public"."comment" to "authenticated";

grant truncate on table "public"."comment" to "authenticated";

grant update on table "public"."comment" to "authenticated";

grant delete on table "public"."comment" to "service_role";

grant insert on table "public"."comment" to "service_role";

grant references on table "public"."comment" to "service_role";

grant select on table "public"."comment" to "service_role";

grant trigger on table "public"."comment" to "service_role";

grant truncate on table "public"."comment" to "service_role";

grant update on table "public"."comment" to "service_role";

grant delete on table "public"."feature" to "anon";

grant insert on table "public"."feature" to "anon";

grant references on table "public"."feature" to "anon";

grant select on table "public"."feature" to "anon";

grant trigger on table "public"."feature" to "anon";

grant truncate on table "public"."feature" to "anon";

grant update on table "public"."feature" to "anon";

grant delete on table "public"."feature" to "authenticated";

grant insert on table "public"."feature" to "authenticated";

grant references on table "public"."feature" to "authenticated";

grant select on table "public"."feature" to "authenticated";

grant trigger on table "public"."feature" to "authenticated";

grant truncate on table "public"."feature" to "authenticated";

grant update on table "public"."feature" to "authenticated";

grant delete on table "public"."feature" to "service_role";

grant insert on table "public"."feature" to "service_role";

grant references on table "public"."feature" to "service_role";

grant select on table "public"."feature" to "service_role";

grant trigger on table "public"."feature" to "service_role";

grant truncate on table "public"."feature" to "service_role";

grant update on table "public"."feature" to "service_role";

grant delete on table "public"."feature_dependencies" to "anon";

grant insert on table "public"."feature_dependencies" to "anon";

grant references on table "public"."feature_dependencies" to "anon";

grant select on table "public"."feature_dependencies" to "anon";

grant trigger on table "public"."feature_dependencies" to "anon";

grant truncate on table "public"."feature_dependencies" to "anon";

grant update on table "public"."feature_dependencies" to "anon";

grant delete on table "public"."feature_dependencies" to "authenticated";

grant insert on table "public"."feature_dependencies" to "authenticated";

grant references on table "public"."feature_dependencies" to "authenticated";

grant select on table "public"."feature_dependencies" to "authenticated";

grant trigger on table "public"."feature_dependencies" to "authenticated";

grant truncate on table "public"."feature_dependencies" to "authenticated";

grant update on table "public"."feature_dependencies" to "authenticated";

grant delete on table "public"."feature_dependencies" to "service_role";

grant insert on table "public"."feature_dependencies" to "service_role";

grant references on table "public"."feature_dependencies" to "service_role";

grant select on table "public"."feature_dependencies" to "service_role";

grant trigger on table "public"."feature_dependencies" to "service_role";

grant truncate on table "public"."feature_dependencies" to "service_role";

grant update on table "public"."feature_dependencies" to "service_role";

grant delete on table "public"."file_comment" to "anon";

grant insert on table "public"."file_comment" to "anon";

grant references on table "public"."file_comment" to "anon";

grant select on table "public"."file_comment" to "anon";

grant trigger on table "public"."file_comment" to "anon";

grant truncate on table "public"."file_comment" to "anon";

grant update on table "public"."file_comment" to "anon";

grant delete on table "public"."file_comment" to "authenticated";

grant insert on table "public"."file_comment" to "authenticated";

grant references on table "public"."file_comment" to "authenticated";

grant select on table "public"."file_comment" to "authenticated";

grant trigger on table "public"."file_comment" to "authenticated";

grant truncate on table "public"."file_comment" to "authenticated";

grant update on table "public"."file_comment" to "authenticated";

grant delete on table "public"."file_comment" to "service_role";

grant insert on table "public"."file_comment" to "service_role";

grant references on table "public"."file_comment" to "service_role";

grant select on table "public"."file_comment" to "service_role";

grant trigger on table "public"."file_comment" to "service_role";

grant truncate on table "public"."file_comment" to "service_role";

grant update on table "public"."file_comment" to "service_role";

grant delete on table "public"."profile" to "anon";

grant insert on table "public"."profile" to "anon";

grant references on table "public"."profile" to "anon";

grant select on table "public"."profile" to "anon";

grant trigger on table "public"."profile" to "anon";

grant truncate on table "public"."profile" to "anon";

grant update on table "public"."profile" to "anon";

grant delete on table "public"."profile" to "authenticated";

grant insert on table "public"."profile" to "authenticated";

grant references on table "public"."profile" to "authenticated";

grant select on table "public"."profile" to "authenticated";

grant trigger on table "public"."profile" to "authenticated";

grant truncate on table "public"."profile" to "authenticated";

grant update on table "public"."profile" to "authenticated";

grant delete on table "public"."profile" to "service_role";

grant insert on table "public"."profile" to "service_role";

grant references on table "public"."profile" to "service_role";

grant select on table "public"."profile" to "service_role";

grant trigger on table "public"."profile" to "service_role";

grant truncate on table "public"."profile" to "service_role";

grant update on table "public"."profile" to "service_role";

grant delete on table "public"."profile_project" to "anon";

grant insert on table "public"."profile_project" to "anon";

grant references on table "public"."profile_project" to "anon";

grant select on table "public"."profile_project" to "anon";

grant trigger on table "public"."profile_project" to "anon";

grant truncate on table "public"."profile_project" to "anon";

grant update on table "public"."profile_project" to "anon";

grant delete on table "public"."profile_project" to "authenticated";

grant insert on table "public"."profile_project" to "authenticated";

grant references on table "public"."profile_project" to "authenticated";

grant select on table "public"."profile_project" to "authenticated";

grant trigger on table "public"."profile_project" to "authenticated";

grant truncate on table "public"."profile_project" to "authenticated";

grant update on table "public"."profile_project" to "authenticated";

grant delete on table "public"."profile_project" to "service_role";

grant insert on table "public"."profile_project" to "service_role";

grant references on table "public"."profile_project" to "service_role";

grant select on table "public"."profile_project" to "service_role";

grant trigger on table "public"."profile_project" to "service_role";

grant truncate on table "public"."profile_project" to "service_role";

grant update on table "public"."profile_project" to "service_role";

grant delete on table "public"."profile_workspace" to "anon";

grant insert on table "public"."profile_workspace" to "anon";

grant references on table "public"."profile_workspace" to "anon";

grant select on table "public"."profile_workspace" to "anon";

grant trigger on table "public"."profile_workspace" to "anon";

grant truncate on table "public"."profile_workspace" to "anon";

grant update on table "public"."profile_workspace" to "anon";

grant delete on table "public"."profile_workspace" to "authenticated";

grant insert on table "public"."profile_workspace" to "authenticated";

grant references on table "public"."profile_workspace" to "authenticated";

grant select on table "public"."profile_workspace" to "authenticated";

grant trigger on table "public"."profile_workspace" to "authenticated";

grant truncate on table "public"."profile_workspace" to "authenticated";

grant update on table "public"."profile_workspace" to "authenticated";

grant delete on table "public"."profile_workspace" to "service_role";

grant insert on table "public"."profile_workspace" to "service_role";

grant references on table "public"."profile_workspace" to "service_role";

grant select on table "public"."profile_workspace" to "service_role";

grant trigger on table "public"."profile_workspace" to "service_role";

grant truncate on table "public"."profile_workspace" to "service_role";

grant update on table "public"."profile_workspace" to "service_role";

grant delete on table "public"."project" to "anon";

grant insert on table "public"."project" to "anon";

grant references on table "public"."project" to "anon";

grant select on table "public"."project" to "anon";

grant trigger on table "public"."project" to "anon";

grant truncate on table "public"."project" to "anon";

grant update on table "public"."project" to "anon";

grant delete on table "public"."project" to "authenticated";

grant insert on table "public"."project" to "authenticated";

grant references on table "public"."project" to "authenticated";

grant select on table "public"."project" to "authenticated";

grant trigger on table "public"."project" to "authenticated";

grant truncate on table "public"."project" to "authenticated";

grant update on table "public"."project" to "authenticated";

grant delete on table "public"."project" to "service_role";

grant insert on table "public"."project" to "service_role";

grant references on table "public"."project" to "service_role";

grant select on table "public"."project" to "service_role";

grant trigger on table "public"."project" to "service_role";

grant truncate on table "public"."project" to "service_role";

grant update on table "public"."project" to "service_role";

grant delete on table "public"."project_projecttag" to "anon";

grant insert on table "public"."project_projecttag" to "anon";

grant references on table "public"."project_projecttag" to "anon";

grant select on table "public"."project_projecttag" to "anon";

grant trigger on table "public"."project_projecttag" to "anon";

grant truncate on table "public"."project_projecttag" to "anon";

grant update on table "public"."project_projecttag" to "anon";

grant delete on table "public"."project_projecttag" to "authenticated";

grant insert on table "public"."project_projecttag" to "authenticated";

grant references on table "public"."project_projecttag" to "authenticated";

grant select on table "public"."project_projecttag" to "authenticated";

grant trigger on table "public"."project_projecttag" to "authenticated";

grant truncate on table "public"."project_projecttag" to "authenticated";

grant update on table "public"."project_projecttag" to "authenticated";

grant delete on table "public"."project_projecttag" to "service_role";

grant insert on table "public"."project_projecttag" to "service_role";

grant references on table "public"."project_projecttag" to "service_role";

grant select on table "public"."project_projecttag" to "service_role";

grant trigger on table "public"."project_projecttag" to "service_role";

grant truncate on table "public"."project_projecttag" to "service_role";

grant update on table "public"."project_projecttag" to "service_role";

grant delete on table "public"."projecttag" to "anon";

grant insert on table "public"."projecttag" to "anon";

grant references on table "public"."projecttag" to "anon";

grant select on table "public"."projecttag" to "anon";

grant trigger on table "public"."projecttag" to "anon";

grant truncate on table "public"."projecttag" to "anon";

grant update on table "public"."projecttag" to "anon";

grant delete on table "public"."projecttag" to "authenticated";

grant insert on table "public"."projecttag" to "authenticated";

grant references on table "public"."projecttag" to "authenticated";

grant select on table "public"."projecttag" to "authenticated";

grant trigger on table "public"."projecttag" to "authenticated";

grant truncate on table "public"."projecttag" to "authenticated";

grant update on table "public"."projecttag" to "authenticated";

grant delete on table "public"."projecttag" to "service_role";

grant insert on table "public"."projecttag" to "service_role";

grant references on table "public"."projecttag" to "service_role";

grant select on table "public"."projecttag" to "service_role";

grant trigger on table "public"."projecttag" to "service_role";

grant truncate on table "public"."projecttag" to "service_role";

grant update on table "public"."projecttag" to "service_role";

grant delete on table "public"."task" to "anon";

grant insert on table "public"."task" to "anon";

grant references on table "public"."task" to "anon";

grant select on table "public"."task" to "anon";

grant trigger on table "public"."task" to "anon";

grant truncate on table "public"."task" to "anon";

grant update on table "public"."task" to "anon";

grant delete on table "public"."task" to "authenticated";

grant insert on table "public"."task" to "authenticated";

grant references on table "public"."task" to "authenticated";

grant select on table "public"."task" to "authenticated";

grant trigger on table "public"."task" to "authenticated";

grant truncate on table "public"."task" to "authenticated";

grant update on table "public"."task" to "authenticated";

grant delete on table "public"."task" to "service_role";

grant insert on table "public"."task" to "service_role";

grant references on table "public"."task" to "service_role";

grant select on table "public"."task" to "service_role";

grant trigger on table "public"."task" to "service_role";

grant truncate on table "public"."task" to "service_role";

grant update on table "public"."task" to "service_role";

grant delete on table "public"."task_dependencies" to "anon";

grant insert on table "public"."task_dependencies" to "anon";

grant references on table "public"."task_dependencies" to "anon";

grant select on table "public"."task_dependencies" to "anon";

grant trigger on table "public"."task_dependencies" to "anon";

grant truncate on table "public"."task_dependencies" to "anon";

grant update on table "public"."task_dependencies" to "anon";

grant delete on table "public"."task_dependencies" to "authenticated";

grant insert on table "public"."task_dependencies" to "authenticated";

grant references on table "public"."task_dependencies" to "authenticated";

grant select on table "public"."task_dependencies" to "authenticated";

grant trigger on table "public"."task_dependencies" to "authenticated";

grant truncate on table "public"."task_dependencies" to "authenticated";

grant update on table "public"."task_dependencies" to "authenticated";

grant delete on table "public"."task_dependencies" to "service_role";

grant insert on table "public"."task_dependencies" to "service_role";

grant references on table "public"."task_dependencies" to "service_role";

grant select on table "public"."task_dependencies" to "service_role";

grant trigger on table "public"."task_dependencies" to "service_role";

grant truncate on table "public"."task_dependencies" to "service_role";

grant update on table "public"."task_dependencies" to "service_role";

grant delete on table "public"."workspace" to "anon";

grant insert on table "public"."workspace" to "anon";

grant references on table "public"."workspace" to "anon";

grant select on table "public"."workspace" to "anon";

grant trigger on table "public"."workspace" to "anon";

grant truncate on table "public"."workspace" to "anon";

grant update on table "public"."workspace" to "anon";

grant delete on table "public"."workspace" to "authenticated";

grant insert on table "public"."workspace" to "authenticated";

grant references on table "public"."workspace" to "authenticated";

grant select on table "public"."workspace" to "authenticated";

grant trigger on table "public"."workspace" to "authenticated";

grant truncate on table "public"."workspace" to "authenticated";

grant update on table "public"."workspace" to "authenticated";

grant delete on table "public"."workspace" to "service_role";

grant insert on table "public"."workspace" to "service_role";

grant references on table "public"."workspace" to "service_role";

grant select on table "public"."workspace" to "service_role";

grant trigger on table "public"."workspace" to "service_role";

grant truncate on table "public"."workspace" to "service_role";

grant update on table "public"."workspace" to "service_role";